### ISSUE TITLE
Emojis doesn't show up on Windows Terminal

### ISSUE THREAD

**Issue by jarmos-san** [xiyaowong/telescope-emoji.nvim#2]
I'm using Windows Terminal & have loaded the extension as suggested, yet the emojis doesn't show up on the window. Any idea why is it so? Or at least can help me debug it further?

Also, just a heads up for you, I'm pretty sure Windows Terminal does support emojis because I've seen other terminal apps showing them. And I've attached a screenshot for your reference:

![image](https://user-images.githubusercontent.com/31373860/128043999-96d8c3b3-a7a1-41d1-adf4-41c797d8c55c.png)

**Comment by xiyaowong** [comment]
The demo gif in readme is using win termunal. So I don't know what the problem is. It seems very likely that the problem is the font

**Comment by jarmos-san** [comment]
> The demo gif in readme is using win termunal. So I don't know what the problem is. It seems very likely that the problem is the font

Hmm...I see. I'm using a Fira Code Nerd Font though & have never faced issues with emojis before. I really wonder what went wrong with it though.

**Comment by xiyaowong** [comment]
try simply copy and paste these emojis😃😆👍

**Comment by jarmos-san** [comment]
> try simply copy and paste these emojis😃😆👍

Ha...interesting! I copied those emojis to my terminal & guess what? This is what I found out:

![image](https://user-images.githubusercontent.com/31373860/128047637-cdc19082-888e-44d0-a852-23a2e41ba896.png)

So, looks like I'm definitely missing something out here.

**Comment by jarmos-san** [comment]
So, I tried digging around a bit more, and found out Emoji support on Windows Terminal is still pretty much unstable as is suggested [in this comment](https://github.com/microsoft/terminal/issues/190#issuecomment-650842083) & this [StackOverflow answer](https://stackoverflow.com/questions/64940181/cannot-display-emojis-in-windows-powershell-or-wsl-linux-terminal-using-python).

If the problem persists & isn't directly related to `telescope-emoji.nvim` then it does make sense to follow issue thread [#190](https://github.com/microsoft/terminal/issues/190) in the Windows Terminal repository.

**Comment by xiyaowong** [comment]
👍
