### ISSUE TITLE
Insert the chosen emoji when picked

### ISSUE THREAD

**Issue by tobias-z** [xiyaowong/telescope-emoji.nvim#5]
Hey thank you for taking the time to create this extension!

I have installed your extension and it seems to work great.

Because you expose the ability to configure what should be done when an emoji is chosen i was able to insert the emoji directly instead of having to put press p afterwards.

```lua
require("telescope-emoji").setup({
    action = function(emoji)
        vim.api.nvim_command(string.format(':call feedkeys("i"."%s")', emoji.value))
    end,
})
```

I'm unsure if the current design is what you want it to do, and if so that's fine, however if it is then maybe this functionality should be documented in the readme

**Comment by xiyaowong** [comment]
```lua
vim.api.nvim_put({ emoji.value }, 'c', false, true)
``` 
would be better

**Comment by tobias-z** [comment]
> ```lua
> vim.api.nvim_put({ emoji.value }, 'c', false, true)
> ```
> 
> would be better

Sounds good to me, i'm no master in the best functions to use which is prob why the documentation of said functionality would be great :laughing:

**Comment by hrqmonteiro** [comment]
> vim.api.nvim_put({ emoji.value }, 'c', false, true)

<s>Not working, is there a modern alternative to directly paste it when picked? Please</s>

Actually nevermind, i made it work
